### ISSUE TITLE
Raspberry Pi Zero W

### ISSUE THREAD

**Issue by bert2002** [jarret/raspi-uart-waveshare#2]
Hi,
have you tried using the library on a Pi Zero W. The pinouts should be the same, but I can't get it work. When I switch to a 3B+ it works immediately. 
Any idea?

Many thanks,
bert

**Comment by jarret** [comment]
My first thought is that there is the known conflict between the UART port and the bluetooth module on some of the Pis.
https://raspberrypi.stackexchange.com/questions/62722/pi-zero-w-wifi-interference-with-tty
On my Pi 3B (non-plus), I have `enable_uart=1` and `dtoverlay=pi3-disable-bt` set in `/boot/config.txt`. I haven't tried with the 3B+, but upon hardware revision they might have fixed the thing that was causing the conflict. It might just work there alongside the bluetooth. The Zero W seems to have the same conflict problem as the 3B from what I am reading. I have never tried it on that board myself.

Let me know if you get it working and what the issue was.

Cheers

**Comment by bert2002** [comment]
Got myself one with Pinouts on it and it seems that it was caused by my cabling before. Now it works as with the 3B+.
